zookeeper:
  # zookeeper的地址 除了开发环境，不推荐填localhost、127.0.0.1之类的配置
  registry-host: ${ZOOKEEPER_HOST:127.0.0.1}
  registry-port: ${ZOOKEEPER_PORT:2181}
  # 本机网卡ip地址，开发、生产都禁止填localhost、127.0.0.1之类的配置
  instance-host: ${SERVER_HOST:192.168.0.2}

# 一般不需要动，懂的可以定制
spring:
  cloud:
    zookeeper:
      register: true
      enabled: true
      connect-string: ${zookeeper.registry-host}:${zookeeper.registry-port}
      discovery:
        instance-host: ${zookeeper.instance-host}
