spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Sonic云真机测试平台 - 网关"
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @project.artifactId@,actuator,zookeeper,logging,user
